name: Statistische Auswertung

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas matplotlib
#token
    - name: Run Auswertung
      run: python auswertung.py
      env:
        MDE_TOKEN: ${{ secrets.MDE_TOKEN }}

    - name: Commit Results
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@users.noreply.github.com"
        git add .
        git commit -m "Update results"
        git push --token ${{ secrets.MDE_TOKEN }} origin master
